"""Add email_sends table

Revision ID: 56c4441e94c4
Revises: 890db74cce3f
Create Date: 2025-08-03 21:48:32.172383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c4441e94c4'
down_revision: Union[str, Sequence[str], None] = '890db74cce3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_sends',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('playlist_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('client_ip', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_sends')
    # ### end Alembic commands ###
