"""Initial schema with user sessions, search sessions, and analytics

Revision ID: 5851307274f8
Revises: 
Create Date: 2025-08-03 16:16:05.897162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5851307274f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('user_session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_session_id')
    )
    op.create_table('playlists',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_session_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('track_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_session_id'], ['user_sessions.user_session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_sessions',
    sa.Column('search_session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('original_query', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_turns', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_session_id'], ['user_sessions.user_session_id'], ),
    sa.PrimaryKeyConstraint('search_session_id')
    )
    op.create_table('search_jobs',
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('search_session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('conversation_turn', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('has_image', sa.Boolean(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('filters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_message', sa.Text(), nullable=True),
    sa.Column('llm_reflection', sa.Text(), nullable=True),
    sa.Column('chain_of_thought', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['search_session_id'], ['search_sessions.search_session_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('search_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('search_session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('conversation_turn', sa.Integer(), nullable=False),
    sa.Column('spotify_track_id', sa.String(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['search_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('search_session_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('spotify_track_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('conversation_turn', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['search_jobs.job_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_events')
    op.drop_table('search_results')
    op.drop_table('search_jobs')
    op.drop_table('search_sessions')
    op.drop_table('playlists')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
