"""link_playlists_to_search_sessions

Revision ID: 890db74cce3f
Revises: cef585a46b38
Create Date: 2025-08-03 20:50:31.920641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890db74cce3f'
down_revision: Union[str, Sequence[str], None] = 'cef585a46b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('search_session_id', sa.UUID(as_uuid=False), nullable=False))
    op.drop_constraint(op.f('playlists_user_session_id_fkey'), 'playlists', type_='foreignkey')
    op.create_foreign_key(None, 'playlists', 'search_sessions', ['search_session_id'], ['search_session_id'])
    op.drop_column('playlists', 'user_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('user_session_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'playlists', type_='foreignkey')
    op.create_foreign_key(op.f('playlists_user_session_id_fkey'), 'playlists', 'user_sessions', ['user_session_id'], ['user_session_id'])
    op.drop_column('playlists', 'search_session_id')
    # ### end Alembic commands ###
