"""Add client_ip to user_sessions and has_image to search_sessions

Revision ID: 9de88be7d6e1
Revises: 5851307274f8
Create Date: 2025-08-03 16:55:20.811266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de88be7d6e1'
down_revision: Union[str, Sequence[str], None] = '5851307274f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_sessions', sa.Column('has_image', sa.Boolean(), nullable=True))
    op.add_column('user_sessions', sa.Column('client_ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'client_ip')
    op.drop_column('search_sessions', 'has_image')
    # ### end Alembic commands ###
