"""remove_total_turns_from_search_sessions

Revision ID: cef585a46b38
Revises: d875bbe54197
Create Date: 2025-08-03 18:45:05.852411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef585a46b38'
down_revision: Union[str, Sequence[str], None] = 'd875bbe54197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_sessions', 'total_turns')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_sessions', sa.Column('total_turns', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
