"""Add model_used to search_sessions

Revision ID: d875bbe54197
Revises: 9abad8a3becb
Create Date: 2025-08-03 17:47:20.571285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd875bbe54197'
down_revision: Union[str, Sequence[str], None] = '9abad8a3becb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_sessions', sa.Column('model_used', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_sessions', 'model_used')
    # ### end Alembic commands ###
